apiVersion: v1
entries:
  app:
  - apiVersion: v2
    appVersion: 0.0.0
    created: "2024-09-19T00:29:29.172486562+03:00"
    description: A Helm chart for Kubernetes
    digest: 5acdfa12f7848056d4d939d77812c64b1c4c52c759d7bbfa4cd94969c58538ce
    name: app
    type: application
    urls:
    - https://shaharby7.github.io/Dope/helm/charts/app-0.1.0.tgz
    version: 0.1.0
  argo-crds:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-09-19T00:29:29.175196025+03:00"
    description: A Helm chart for Kubernetes
    digest: aca397acde1b49ea3e5d8f6b3df987fb43657af99a670bb90d452e7ded32f1fa
    name: argo-crds
    type: application
    urls:
    - https://shaharby7.github.io/Dope/helm/charts/argo-crds-0.1.0.tgz
    version: 0.1.0
  dope:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-09-19T00:29:29.189529791+03:00"
    dependencies:
    - condition: providers.argo-cd.managed
      name: argo-cd
      repository: https://argoproj.github.io/argo-helm
      version: 6.8.1
    - condition: providers.argo-workflows.managed
      name: argo-workflows
      repository: https://argoproj.github.io/argo-helm
      version: 0.41.4
    - condition: providers.argo-cd.managed
      name: argo-crds
      repository: https://shaharby7.github.io/Dope/helm/charts
      version: 0.1.0
    - name: dope-ci
      repository: https://shaharby7.github.io/Dope/helm/charts
      version: 0.1.0
    description: A Helm chart for Kubernetes
    digest: 073712c9dc1d14ed2d6dce9d1412e78befd5df51d94b5859ba43e38afe76d9f3
    name: dope
    type: application
    urls:
    - https://shaharby7.github.io/Dope/helm/charts/dope-0.1.0.tgz
    version: 0.1.0
  dope-ci:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-09-19T00:29:29.189685253+03:00"
    description: A Helm chart for Kubernetes
    digest: 9b6012197912a85a297fd2ad4f356ed6ad6f8d3d3e781c66e42a0936077d0125
    name: dope-ci
    type: application
    urls:
    - https://shaharby7.github.io/Dope/helm/charts/dope-ci-0.1.0.tgz
    version: 0.1.0
generated: "2024-09-19T00:29:29.171632125+03:00"
