---
# Source: application-manager/templates/applications-project.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: applications
---
# Source: application-manager/templates/applications-project.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: Viewer
  namespace: applications
rules:
  - apiGroups:
      - ""
    verbs:
      - "*"
    resources:
      - "*"
---
# Source: application-manager/templates/applications-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject  
metadata:
  name: applications
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: One project to rule them all
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the applications namespace in the same cluster
  destinations:
    - namespace: applications
      server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
  roles:
    - description: Service deployment role
      groups:
        - application-launcher
      name: application-launcher-admin
      policies:
        - p, proj:application-launcher:application-launcher-admin, applications, *, application-launcher/*, allow
---
# Source: application-manager/templates/manager-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: application-manager
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: One project to rule them all
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the runspace namespace in the same cluster
  destinations:
    - namespace: dope
      server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
  roles:
    - description: Service deployment role
      groups:
        - application-manager
      name: application-manager-admin
      policies:
        - p, proj:application-manager:application-manager-admin, applications, *, application-manager/*, allow
---
# Source: application-manager/templates/manager-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-list
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: application-manager
  source:
    repoURL: https://shaharby7.github.io/Dope/helm/charts
    chart: "applications-list"
    targetRevision: 0.1.0
    helm:
      values:
        environment: local
        sources:
         app1:
           chart: application
           helm:
             releaseName: app1
             valueFiles:
             - https://raw.githubusercontent.com/shaharby7/Dope/example/example/build/helm/values/local/app1/values.yaml
             - https://raw.githubusercontent.com/shaharby7/Dope/example/example/build/helm/values/local/app1/apps.yaml
             - https://raw.githubusercontent.com/shaharby7/Dope/example/example/build/helm/values/local/app1/image.yaml
           repoURL: https://shaharby7.github.io/Dope/helm/charts
           targetRevision: 0.1.0
      releaseName: applications-list
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dope
  syncPolicy:
    automated:
      prune: true
