argo-cd:
  crds:
    install: false
  enabled: true
  redis-ha:
    enabled: false
  controller:
    replicas: 1
  server:
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicaCount: 1

argo-workflows:
  crds:
    install: false
  enabled: true
  server:
    extraArgs: [--auth-mode=server]
    clusterWorkflowTemplates:
      enabled: true
  controller:
    workflowNamespaces:
    - dope
    rbac:
      create: true
    clusterWorkflowTemplates:
      enabled: true

dope-ci:
  enabled: true

application-manager:
  enabled: true
  environment: local
  sources:
    app1:
      repoURL: https://shaharby7.github.io/Dope/helm/charts
      targetRevision: 0.1.0
      chart: application
      helm:
        releaseName: app1
        valueFiles:
        - https://raw.githubusercontent.com/shaharby7/Dope/example/example/build/helm/values/local/app1/values.yaml
        - https://raw.githubusercontent.com/shaharby7/Dope/example/example/build/helm/values/local/app1/apps.yaml
        - https://raw.githubusercontent.com/shaharby7/Dope/example/example/build/helm/values/local/app1/image.yaml
