{{- range $controller := .Values.controllers }}
---
{{- $includeValues := dict "root" $ "controller" $controller }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "controller.fullname" $includeValues }}
  labels:
    {{- include "controller.labels" $includeValues | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "controller.selectorLabels" $includeValues | nindent 6 }}
  {{- if not (and $controller.autoscaling $controller.autoscaling.enabled) }}
  replicas: {{ $controller.replicaCount }}
  {{- end }}
  template:
    metadata:
      {{- if $.Values.pod }}
      {{- with $.Values.pod.annotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "controller.labels" $includeValues | nindent 8 }}
        {{- if $.Values.pod }} 
        {{- with $.Values.pod.labels }}
        {{- toYaml $ | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" $ }}
      securityContext:
        {{- if $.Values.pod }}
        {{- toYaml $.Values.pod.securityContext | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "controller.fullname" $includeValues }}
          securityContext:
            {{- if $.Values.pod }}
            {{- toYaml $.Values.pod.securityContext | nindent 12 }}
            {{- end }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $controller.resources | nindent 12 }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml $ | nindent 12 }}
          {{- end }}
          env:
           {{- (include "controller.env" $includeValues) | nindent 12 }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
{{- end }}
