argo-cd:
  enabled: true
  redis-ha:
    enabled: false
  controller:
    replicas: 1
  server:
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicaCount: 1

argo-workflows:
  enabled: true

ci:
  enabled: true
