{{- range $name, $values:= .Values.sources}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: runspace
  source:
    {{- $values | toYaml | nindent 4}}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: runspace
  {{- if eq "local" $.Values.environment}}
  syncPolicy:
    automated:
      prune: true
  {{- end }}
{{- end}}