{{- range $app := .Values.apps}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
spec:
  project: {{ include "appsProjectName" $ }}
  destination:
    server: https://kubernetes.{{include "appsProjectName" $ }}.svc
    namespace: {{ include "appsProjectName" $ }}
  sources:
  - repoURL: 'https://https://shaharby7.github.io/Dope/helm/charts'
    chart: app
    targetRevision: 0.1.0
    helm:
      valueFiles:
      {{- range $file := list "image" "values" "apps" }}
      {{- $buildDir :=  default "build" $.Values.project.directories.build }}
      {{- $environment := $.Values.environment.name }}
      - {{ printf "$values/%s/helm/%s/%s/%s.yaml" $buildDir $environment $app.name $file  | clean }}
      {{- end}}
  - repoURL: {{ $.Values.providers.git.url }}
    targetRevision: {{ default "main" $.Values.providers.git.ref }}
    ref: values
    path: {{ default "main" $.Values.providers.git.path }}
{{- end}}