package types

type ENV_VARS string

const (
	ENV_VAR_CONTROLLER      ENV_VARS = "DOPE_CONTROLLER"
	ENV_VAR_HTTPSERVER_PORT ENV_VARS = "DOPE_HTTPSERVER_PORT"
)

type DOPE_PROVIDERS string

const (
	DOPE_PROVIDER_MINIKUBE DOPE_PROVIDERS = "minikube"
)

const HTTPSERVER_DEFAULT_PORT = 3000
