package types

type ENV_VARS string

const (
	ENV_VAR_CONTROLLER_NAME ENV_VARS = "DOPE_CONTROLLER_NAME"
	ENV_VAR_CONTROLLER_TYPE ENV_VARS = "DOPE_CONTROLLER_TYPE"
	ENV_VAR_APP_NAME        ENV_VARS = "DOPE_APP_NAME"
	ENV_VAR_HTTPSERVER_PORT ENV_VARS = "DOPE_HTTPSERVER_PORT"
	ENV_VAR_DOPE_PORT       ENV_VARS = "DOPE_DOPE_PORT"
)

type DOPE_PROVIDERS string

const (
	DOPE_PROVIDER_MINIKUBE DOPE_PROVIDERS = "minikube"
)

const HTTPSERVER_DEFAULT_PORT = 3000
