package types

type ENV_VARS string

const (
	ENV_VARS_CONTROLLER      ENV_VARS = "DOPE_CONTROLLER"
	ENV_VARS_HTTPSERVER_PORT ENV_VARS = "DOPE_HTTPSERVER_PORT"
)

const HTTPSERVER_DEFAULT_PORT = 3000
