{{- range $app, $val := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" $ }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application.labels" $ | nindent 8 }}
        {{- with .podLabels }}
        {{- toYaml $ | nindent 8 }}
        {{- end }}
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "application.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml $ | nindent 12 }}
          {{- end }}
          {{- if or $.Values.env .env -}}
          {{- $mergedEnv := mergeOverwrite ($.Values.env | default (dict)) (.env | default (dict)) }}
          env:
          - name: DOPE_CONTROLLER
            value: "server1"
          - name: DOPE_HTTPSERVER_PORT
            value: "3000"
          {{ range $key, $value := $mergedEnv }}
          - name: {{ $key }}
            {{- if kindIs "map" $value }}
            {{- toYaml $value | nindent 12 }}
            {{- else }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{ else }}
          env:
          - name: DOPE_CONTROLLER
            value: "server1"
          - name: DOPE_HTTPSERVER_PORT
            value: "3000"
          {{- end }}
      {{- with .volumes }}
      volumes:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
{{- end }}
