apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-workflow-template
  namespace: dope
spec:
  serviceAccountName: ci-sa
  arguments:
    parameters:
      - name: app
  entrypoint: ci
  templates:
    - name: ci
      arguments:
        parameters:
          - name: app
            value: my-app
      steps:
        - - name: hello
            template: hello

    - name: hello
      container:
        image: docker/whalesay
        command: [cowsay]
        args: [ "{{`{{workflow.parameters.app}}`}}" ]
        resources:
          limits:
            memory: 32Mi
            cpu: 100m
