argo-cd:
  crds:
    install: false
  enabled: true
  redis-ha:
    enabled: false
  controller:
    replicas: 1
  server:
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicaCount: 1

argo-workflows:
  crds:
    install: false
  enabled: true
  server:
    extraArgs: [--auth-mode=server]
    clusterWorkflowTemplates:
      enabled: true
  controller:
    workflowNamespaces:
    - dope
    rbac:
      create: true
    clusterWorkflowTemplates:
      enabled: true

dope-ci:
  enabled: true

application-manager:
