controllers:
  - name: "server1"
    type: HTTPServer
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 12
      targetCPUUtilizationPercentage: 90
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 8Gi
