
appName: app1

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

imagePullSecrets: []

pod:
  annotations: {}
  labels: {}
  securityContext: {}

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
