apiVersion: v2
name: dope
description: A Helm chart for Kubernetes

type: application

version: 0.1.4

appVersion: "1.16.0"

dependencies:
- name: argo-cd
  version: "7.6.1"
  repository: "https://argoproj.github.io/argo-helm"
  condition: providers.argo-cd.managed
- name: argo-crds
  version: "0.1.0"
  repository: "https://shaharby7.github.io/Dope/helm/charts"
  condition: providers.argo-cd.managed
- name: argo-workflows
  version: "0.41.4"
  repository: "https://argoproj.github.io/argo-helm"
  condition: providers.argo-workflows.managed
- name: dope-ci
  version: "0.1.0"
  repository: "https://shaharby7.github.io/Dope/helm/charts"
