project:
  name: example
  description: "project example"
  dopeVersion: 0.0.1
  module: github.com/shaharby7/Dope/example
  versioning:
    granularity: "app" # "app | project"
    version: 0.0.1

build:
  path: ./example/build

apps:
- name: "app1"

environment:
  name: local
# appsProjectNameOverride: applications

providers:
  git:
    url: https://github.com/shaharby7/Dope.git
    path: example
    ref: shahar
  kubernetes:
    type: minikube
  docker:
    registry: docker.io
    prefix: shaharby7 #TODO: add username and password support
  storage:
    type: minio
    managed: false
  cd:
    type: argo-cd
    managed: true
  workflows:
    type: argo-workflows
    managed: false

argo-cd:
  crds:
    install: false
  redis-ha:
    enabled: false
  controller:
    replicas: 1
  server:
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicaCount: 1

# argo-workflows:
#   crds:
#     install: false
#   server:
#     extraArgs: [ --auth-mode=server ]
#     clusterWorkflowTemplates:
#       enabled: true
#   controller:
#     workflowNamespaces:
#     - dope
#     rbac:
#       create: true
#     clusterWorkflowTemplates:
#       enabled: true
