env:
- name: UGLY_NAMES
  value: "shahar,hadas"

# replicas: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 1
    memory: 2GB
  limits:
    cpu: 2
    memory: 4GB

debug:
  enabled: true
  port: 4000
