package v1

type DOPE_CORE_TYPES string

const (
	DOPE_CORE_TYPES_PROJECT DOPE_CORE_TYPES = "Project"
	DOPE_CORE_TYPES_APP     DOPE_CORE_TYPES = "App"
	DOPE_CORE_TYPES_ENV     DOPE_CORE_TYPES = "Env"
	DOPE_CORE_TYPES_APPENV  DOPE_CORE_TYPES = "AppEnv"
)