apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: One project to rule them all
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the applications namespace in the same cluster
  destinations:
    - namespace: applications
      server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
  roles:
    - description: Service deployment role
      groups:
        - application-launcher
      name: application-launcher-admin
      policies:
        - p, proj:application-launcher:application-launcher-admin, applications, *, application-launcher/*, allow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: Viewer
  namespace: applications
rules:
  - apiGroups:
      - ""
    verbs:
      - "*"
    resources:
      - "*"
