apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: application-manager
  source:
    repoURL: https://shaharby7.github.io/Dope/helm/charts
    chart: "applications-list"
    targetRevision: 0.1.0
    values:
      environment: {{ .Values.environment }}
      sources: {{- .Values.sources | toYaml | nindent 7 }}
    helm:
      releaseName: application-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  {{- if eq "local" $.Values.environment}}
  syncPolicy:
    automated:
      prune: true
  {{- end }}
